import { Header } from "@/common-components/src/components/DataTable";

export const headerList: Header[] = [
  {
    text: `Файл`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `filePath`,
    width: 80,
  },
  {
    text: `iNode`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `iNode`,
    width: 80,
  },
  {
    text: `Тип`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `type`,
    width: 80,
  },
  {
    text: `Версия файла`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `fileVersion`,
    width: 80,
  },
  {
    text: `Процесс`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `process`,
    width: 80,
  },
  {
    text: `Версия процесса`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `processVersion`,
    width: 80,
  },
  {
    text: `Оригинальный файл`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `originFile`,
    width: 80,
  },
  {
    text: `Количество`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `count`,
    width: 80,
  },
  {
    text: `Глубина`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `depth`,
    width: 80,
  },
  {
    text: `Пользователь`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `user`,
    width: 80,
  },
  {
    text: `First At`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `firstAt`,
    width: 80,
  },
  {
    text: `Last At`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `lastAt`,
    width: 80,
  },
  {
    text: `Размер`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `initialSizeBytes`,
    width: 80,
  },
  {
    text: `Старт отслеживания`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `trackingStartAt`,
    width: 80,
  },
  {
    text: `Дата удаления`,
    align: "center",
    isVisible: true,
    sortable: true,
    value: `deletedAt`,
    width: 80,
  },
]